<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><ApplicationManifest>app.manifest</ApplicationManifest><ApplicationIcon>..\..\assets\app.ico</ApplicationIcon></PropertyGroup><ItemGroup><ProjectReference Include="../WindowsIntegration/WindowsIntegration.csproj" /></ItemGroup></Project>
